### ISSUE TITLE
Inductive coupling

### ISSUE THREAD

**Issue by jebej** [PhilippAumann/circuitq#10]
Hello, can CircuitQ handle mutual inductive coupling at the moment?

**Comment by PhilippAumann** [comment]
Hi,

CircuitQ treats the circuit as a whole, which means that a numerical matrix is generated which implements the symbolic Hamiltonian describing the circuit. Currently, there is no modular functionality which considers the coupling of separate subsystems or qubits. Adding such a feature would definitely be interesting but goes beyond the current scope of CircuitQ.
